### ISSUE TITLE
mvn package fails with errors. 

### ISSUE THREAD

**Issue by ZeerDonker** [kfrancis/Chargify.Java#2]
Hello,

mvn package fails with errors. 

[ERROR] C:...\Chargify.Java\Chargify.Java\src\main\java\com\chargify\core\http\ResponseErrors.java:[35,7] error: ResponseErrors is not abstract and does not override abstract method remove() in Iterator
[ERROR] -> [Help 1]

[ERROR] C:...\Chargify.Java\Chargify.Java\src\main\java\com\char
gify\core\resources\Customer.java:[31,22] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] C:...\Chargify.Java\Chargify.Java\src\main\java\com\char
gify\core\http\ListResponse.java:[36,7] error: ListResponse is not abstract and does not override abstract method remove() in Iterator

I don't know if this link will help or not:
http://stackoverflow.com/questions/16374189/notimplementedexception-is-internal-proprietary-api

A prev version did build. ( Tests failed, 
 mvn package -Dmaven.test.skip=true , but did build. ) 

The commit that breaks the build is the following. 
"refactored all singular customer methods to use response object to stop using exceptions as control flow"

**Comment by jeremywrowe** [comment]
@ZeerDonker This project is still a work in progress. We are still working out the implementation details. Also note that this is java 1.7+ for the time being.
